
language: cpp

matrix:
  include:
    # linux/gcc/debug/dummy
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy
    # linux/gcc/debug/qt5
    - compiler: gcc
      os: linux
      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5
    # linux/gcc/release/dummy
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy
    # linux/gcc/release/qt5
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5
    # linux/clang/debug/dummy
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy
    # linux/clang/debug/qt5
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5
    # linux/clang/release/dummy
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy
    # linux/clang/release/qt5
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5
    # osx/clang/debug/dummy
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy
    # osx/clang/debug/qt5
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5
    # osx/clang/release/dummy
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy
    # osx/clang/release/qt5
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5

before_install:
  - build/travis-install.sh

script:
  - build/travis-build.sh
