
language: cpp

sudo: required

matrix:
  include:
    # linux/gcc/debug/dummy
    - compiler: gcc
      os: linux
      env: I='-c -g' C='-b Debug -s dummy'
    # linux/gcc/debug/qt5
    - compiler: gcc
      os: linux
      env: I='-c -g -q' C='-b Debug -s qt5 -q /opt/qt54/lib/cmake'
    # linux/gcc/release/dummy
#    - compiler: gcc
#      os: linux
#      env: I='-c -g' C='-b Release -s dummy'
    # linux/gcc/release/qt5
#    - compiler: gcc
#      os: linux
#      env: I='-c -g -q' C='-b Release -s qt5 -q /opt/qt54/lib/cmake'
    # linux/clang/debug/dummy
#    - compiler: clang
#      os: linux
#      env: I='-c' C='-b Debug -s dummy'
    # linux/clang/debug/qt5
#    - compiler: clang
#      os: linux
#      env: I='-c -q' C='-b Debug -s qt5 -q /opt/qt54/lib/cmake'
    # linux/clang/release/dummy
#    - compiler: clang
#      os: linux
#      env: I='-c' C='-b Release -s dummy'
    # linux/clang/release/qt5
#    - compiler: clang
#      os: linux
#      env: I='-c' C='-b Release -s qt5 -q /opt/qt54/lib/cmake'
    # linux/mingw-w32/debug/dummy
    # linux/mingw-w32/debug/qt5
    # linux/mingw-w32/release/dummy
    # linux/mingw-w32/release/qt5
    # osx/clang/debug/dummy
    # osx/clang/debug/qt5
    # osx/clang/release/dummy
    # osx/clang/release/qt5
    # documentation
    - compiler: clang
      os: linux
      env: I='-x' C='-x'

before_install:
  - openssl aes-256-cbc -K $encrypted_b705a8d4577f_key -iv $encrypted_b705a8d4577f_iv -in build/id.enc -out build/id -d
  - build/travis-install.py $I

script:
  - build/travis-build.py $C

notifications:
  email:
    recipients:
      - zapolnov@gmail.com
    on_success: change
    on_failure: always
