
language: cpp

sudo: required

matrix:
  include:
    # linux/gcc/debug/dummy
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy
    # linux/gcc/debug/qt5
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/opt/qt54/lib/cmake
    # linux/gcc/release/dummy
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy
    # linux/gcc/release/qt5
#    - compiler: gcc
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/opt/qt54/lib/cmake
    # linux/clang/debug/dummy
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy
    # linux/clang/debug/qt5
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/opt/qt54/lib/cmake
    # linux/clang/release/dummy
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy
    # linux/clang/release/qt5
#    - compiler: clang
#      os: linux
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/opt/qt54/lib/cmake
    # osx/clang/debug/dummy
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
    # osx/clang/debug/qt5
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
    # osx/clang/release/dummy
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=dummy CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
    # osx/clang/release/qt5
#    - compiler: clang
#      os: osx
#      env: CMAKE_BUILD_TYPE=Release Z_TARGET_PLATFORM=qt5 CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
    # documentation
    - compiler: clang
      os: linux
      env: CMAKE_BUILD_TYPE=Debug Z_TARGET_PLATFORM=dummy Z_DOXYGEN=TRUE

before_install:
  - openssl aes-256-cbc -K $encrypted_b705a8d4577f_key -iv $encrypted_b705a8d4577f_iv -in build/id.enc -out build/id -d
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      build/travis-install-linux.sh;
    fi

script:
  - if [ "${Z_DOXYGEN}" = "TRUE" ]; then
      build/travis-build-documentation.sh;
    else
      build/travis-build.sh;
    fi

notifications:
  email:
    recipients:
      - zapolnov@gmail.com
    on_success: change
    on_failure: always
