
language: android

sudo: required

android:
  components:
    - build-tools-22.0.1
#    - android-15
#    - extra-google-google_play_services
#    - addon-google_apis-google-15

matrix:
  include:
    # linux/gcc/debug/qt5
    - os: linux
      jdk: 'oraclejdk8'
      env: I='-b -c -g -q' C='-b Debug -q /opt/qt54/lib/cmake'
    # linux/gcc/release/dummy
    # linux/gcc/release/qt5
    # linux/clang/debug/dummy
    # linux/clang/debug/qt5
    # linux/clang/release/dummy
    # linux/clang/release/qt5
    # linux/mingw-w32/debug/dummy
    # linux/mingw-w32/debug/qt5
    # linux/mingw-w32/release/dummy
    # linux/mingw-w32/release/qt5
    # osx/clang/debug/dummy
    # osx/clang/debug/qt5
    # osx/clang/release/dummy
    # osx/clang/release/qt5
    # documentation
    - os: linux
      jdk: 'oraclejdk8'
      env: I='-b -x' C='-x'

before_install:
  - openssl aes-256-cbc -K $encrypted_b705a8d4577f_key -iv $encrypted_b705a8d4577f_iv -in build/id.enc -out build/id -d
  - build/travis-install.py $I

script:
  - build/travis-build.py $C

notifications:
  email:
    recipients:
      - zapolnov@gmail.com
    on_success: change
    on_failure: always
