/*
 * Copyright (c) 2014 Nikolay Zapolnov (zapolnov@gmail.com).
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// GL_IMG_texture_compression_pvrtc
Z_GL_CONSTANT_(COMPRESSED_RGB_PVRTC_4BPPV1_IMG, 0x8C00)
Z_GL_CONSTANT_(COMPRESSED_RGB_PVRTC_2BPPV1_IMG, 0x8C01)
Z_GL_CONSTANT_(COMPRESSED_RGBA_PVRTC_4BPPV1_IMG, 0x8C02)
Z_GL_CONSTANT_(COMPRESSED_RGBA_PVRTC_2BPPV1_IMG, 0x8C03)

// GL_OES_compressed_ETC1_RGB8_texture
Z_GL_CONSTANT_(ETC1_RGB8_OES, 0x8D64)

// GL_EXT_texture_compression_s3tc, GL_EXT_texture_compression_dxt1
Z_GL_CONSTANT_(COMPRESSED_RGB_S3TC_DXT1_EXT, 0x83F0)
Z_GL_CONSTANT_(COMPRESSED_RGBA_S3TC_DXT1_EXT, 0x83F1)
Z_GL_CONSTANT_(COMPRESSED_RGBA_S3TC_DXT3_EXT, 0x83F2)
Z_GL_CONSTANT_(COMPRESSED_RGBA_S3TC_DXT5_EXT, 0x83F3)

// GL_ARB_texture_compression_bptc
Z_GL_CONSTANT_(COMPRESSED_RGBA_BPTC_UNORM_ARB, 0x8E8C)
Z_GL_CONSTANT_(COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB, 0x8E8D)
Z_GL_CONSTANT_(COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB, 0x8E8E)
Z_GL_CONSTANT_(COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB, 0x8E8F)

// GL_3DFX_texture_compression_FXT1
Z_GL_CONSTANT_(COMPRESSED_RGB_FXT1_3DFX, 0x86B0)
Z_GL_CONSTANT_(COMPRESSED_RGBA_FXT1_3DFX, 0x86B1)

// GL_EXT_texture_compression_rgtc, GL_ARB_texture_compression_rgtc
Z_GL_CONSTANT_(COMPRESSED_RED_RGTC1_EXT, 0x8DBB)
Z_GL_CONSTANT_(COMPRESSED_SIGNED_RED_RGTC1_EXT, 0x8DBC)
Z_GL_CONSTANT_(COMPRESSED_RED_GREEN_RGTC2_EXT, 0x8DBD)
Z_GL_CONSTANT_(COMPRESSED_SIGNED_RED_GREEN_RGTC2_EXT, 0x8DBE)

// GL_EXT_texture_compression_latc, GL_NV_texture_compression_latc
Z_GL_CONSTANT_(COMPRESSED_LUMINANCE_LATC1_EXT, 0x8C70)
Z_GL_CONSTANT_(COMPRESSED_SIGNED_LUMINANCE_LATC1_EXT, 0x8C71)
Z_GL_CONSTANT_(COMPRESSED_LUMINANCE_ALPHA_LATC2_EXT, 0x8C72)
Z_GL_CONSTANT_(COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2_EXT, 0x8C73)

// GL_KHR_texture_compression_astc_ldr, GL_KHR_texture_compression_astc_hdr
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_4x4_KHR, 0x93B0)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_5x4_KHR, 0x93B1)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_5x5_KHR, 0x93B2)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_6x5_KHR, 0x93B3)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_6x6_KHR, 0x93B4)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_8x5_KHR, 0x93B5)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_8x6_KHR, 0x93B6)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_8x8_KHR, 0x93B7)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_10x5_KHR, 0x93B8)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_10x6_KHR, 0x93B9)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_10x8_KHR, 0x93BA)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_10x10_KHR, 0x93BB)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_12x10_KHR, 0x93BC)
Z_GL_CONSTANT_(COMPRESSED_RGBA_ASTC_12x12_KHR, 0x93BD)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR, 0x93D0)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR, 0x93D1)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR, 0x93D2)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR, 0x93D3)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR, 0x93D4)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR, 0x93D5)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR, 0x93D6)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR, 0x93D7)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR, 0x93D8)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR, 0x93D9)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR, 0x93DA)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR, 0x93DB)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR, 0x93DC)
Z_GL_CONSTANT_(COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR, 0x93DD)
